name: Swift Dependency Submission
on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    swift-action-detection:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Install Swift
              uses: vapor/swiftly-action@v0.1
              with:
                  toolchain: latest

            - name: Submit Dependencies
              uses: vapor-community/swift-dependency-submission@v0.1
